"""
Jan-Seva AI — Extended Scheme Database (Part 2)
200+ additional schemes: All Tamil Nadu, Central, and lesser-known schemes.
"""

EXTRA_SCHEMES = [
    # ═══════════ TAMIL NADU — ALL REMAINING ═══════════
    {"name": "TN CM Breakfast Scheme", "slug": "tn-cm-breakfast-scheme", "state": "Tamil Nadu", "category": ["Education", "Nutrition", "Children"], "ministry": "Tamil Nadu Education", "benefits": "Free nutritious breakfast for government primary school students (Class 1-5)", "description": "Free breakfast programme for government school children to improve nutrition and school attendance.", "source_url": "https://www.tn.gov.in", "source_type": "html"},
    {"name": "TN Naan Mudhalvan", "slug": "tn-naan-mudhalvan", "state": "Tamil Nadu", "category": ["Education", "Skills", "Youth"], "ministry": "Tamil Nadu Higher Education", "benefits": "Free skill training, industry internships, placement support for college students", "description": "Comprehensive skill development programme for college students with industry partnerships and placement.", "source_url": "https://naanmudhalvan.tn.gov.in", "source_type": "portal"},
    {"name": "TN Kalaignar Magalir Urimai Thogai", "slug": "tn-kalaignar-magalir-urimai", "state": "Tamil Nadu", "category": ["Women", "Cash Transfer"], "ministry": "Tamil Nadu Government", "benefits": "Rs. 1,000 per month cash transfer to women heads of household", "description": "Monthly cash transfer scheme for women family heads to promote financial independence.", "source_url": "https://www.tn.gov.in", "source_type": "html"},
    {"name": "TN Free Rice Scheme", "slug": "tn-free-rice-scheme", "state": "Tamil Nadu", "category": ["Food", "BPL", "Ration"], "ministry": "Tamil Nadu Civil Supplies", "benefits": "20 kg free rice per family card per month for rice cardholders", "description": "Free rice distribution through PDS for all ration card holders in Tamil Nadu.", "source_url": "https://www.tn.gov.in", "source_type": "html"},
    {"name": "TN CM Health Insurance (CMCHIS)", "slug": "tn-cmchis", "state": "Tamil Nadu", "category": ["Health", "Insurance"], "ministry": "Tamil Nadu Health", "benefits": "Rs. 5 lakh health insurance cover per family per year with cashless treatment", "description": "Chief Minister's Comprehensive Health Insurance Scheme providing cashless treatment at empanelled hospitals.", "source_url": "https://www.cmchistn.com", "source_type": "portal"},
    {"name": "TN Free Gold for Marriage", "slug": "tn-free-gold-marriage", "state": "Tamil Nadu", "category": ["Marriage", "Women", "BPL"], "ministry": "Tamil Nadu Social Welfare", "benefits": "4 grams (earlier 8g) of gold for marriage of poor women", "description": "Gold assistance for marriage of women from economically weaker families in Tamil Nadu.", "source_url": "https://www.tnsocialwelfare.tn.gov.in", "source_type": "html"},
    {"name": "TN CM Solar Powered Green House", "slug": "tn-cm-solar-green-house", "state": "Tamil Nadu", "category": ["Housing", "Solar", "Green"], "ministry": "Tamil Nadu Housing", "benefits": "Pucca house with solar panels for BPL families in rural areas", "description": "Housing scheme with integrated solar power for eligible families.", "source_url": "https://www.tn.gov.in", "source_type": "html"},
    {"name": "TN Anaithu Gramma Anna Marumalarchi Thittam", "slug": "tn-anna-marumalarchi", "state": "Tamil Nadu", "category": ["Rural", "Infrastructure", "Development"], "ministry": "Tamil Nadu Rural Development", "benefits": "Village infrastructure development: roads, drainage, streetlights, community halls", "description": "Comprehensive rural development programme for infrastructure upgrades in all villages.", "source_url": "https://www.tn.gov.in", "source_type": "html"},
    {"name": "TN Free Sewing Machine Scheme", "slug": "tn-free-sewing-machine", "state": "Tamil Nadu", "category": ["Women", "Self-Employment"], "ministry": "Tamil Nadu Government", "benefits": "Free sewing machine for women from BPL families for self-employment", "description": "Provides free sewing machines to poor women for income generation.", "source_url": "https://www.tn.gov.in", "source_type": "html"},
    {"name": "TN Free Milch Cow/Goat Scheme", "slug": "tn-free-milch-cow-goat", "state": "Tamil Nadu", "category": ["Animal Husbandry", "Livelihood"], "ministry": "Tamil Nadu Animal Husbandry", "benefits": "Free milch cow or 4 goats + 1 buck for landless poor families", "description": "Livelihood support through free cattle/goat distribution for rural poor.", "source_url": "https://www.tn.gov.in/department/3", "source_type": "html"},
    {"name": "TN Micro Irrigation Subsidy", "slug": "tn-micro-irrigation", "state": "Tamil Nadu", "category": ["Agriculture", "Irrigation", "Subsidy"], "ministry": "Tamil Nadu Agriculture", "benefits": "100% subsidy for drip/sprinkler irrigation for small and marginal farmers", "description": "Full subsidy for micro-irrigation systems to conserve water and improve crop yield.", "source_url": "https://www.tn.gov.in/department/2", "source_type": "html"},
    {"name": "TN Free Electricity for Agriculture", "slug": "tn-free-electricity-agri", "state": "Tamil Nadu", "category": ["Agriculture", "Electricity", "Free"], "ministry": "Tamil Nadu Energy", "benefits": "Free electricity for agricultural pump sets for all farmers", "description": "Free electricity supply for farm pump sets to support agricultural operations.", "source_url": "https://www.tn.gov.in", "source_type": "html"},
    {"name": "TN Samathuvapuram Housing", "slug": "tn-samathuvapuram", "state": "Tamil Nadu", "category": ["Housing", "SC/ST", "Social Justice"], "ministry": "Tamil Nadu Adi Dravidar Welfare", "benefits": "Free houses in mixed-caste colonies promoting social integration", "description": "Housing colonies with mixed-caste allotment to promote social harmony and equality.", "source_url": "https://www.adwelfare.tn.gov.in", "source_type": "html"},
    {"name": "TN Unemployed Youth Allowance", "slug": "tn-unemployed-youth-allowance", "state": "Tamil Nadu", "category": ["Employment", "Youth", "Allowance"], "ministry": "Tamil Nadu Employment", "benefits": "Rs. 1,500 per month for registered unemployed youth graduates", "description": "Monthly allowance for unemployed graduates registered with employment exchange.", "source_url": "https://www.tn.gov.in", "source_type": "html"},
    {"name": "TN Legal Aid Scheme", "slug": "tn-legal-aid", "state": "Tamil Nadu", "category": ["Legal", "Justice", "BPL"], "ministry": "Tamil Nadu Legal Services", "benefits": "Free legal aid and court representation for economically weaker persons", "description": "Free legal services for persons who cannot afford court representation.", "source_url": "https://tnslsa.tn.gov.in", "source_type": "html"},
    {"name": "TN Ilaignar Ani (Youth Programme)", "slug": "tn-ilaignar-ani", "state": "Tamil Nadu", "category": ["Youth", "Development", "Training"], "ministry": "Tamil Nadu Youth Welfare", "benefits": "Leadership training, sports facilities, and cultural programmes for youth", "description": "Youth development programme providing training in leadership, sports, and culture.", "source_url": "https://www.tn.gov.in", "source_type": "html"},
    {"name": "TN Fishermen Housing Scheme", "slug": "tn-fishermen-housing", "state": "Tamil Nadu", "category": ["Housing", "Fishermen"], "ministry": "Tamil Nadu Fisheries", "benefits": "Rs. 3,00,000 for construction of pucca houses for coastal fishermen families", "description": "Housing scheme specifically for fishing community families in coastal areas.", "source_url": "https://www.fisheries.tn.gov.in", "source_type": "html"},
    {"name": "TN Innuyir Kappom (Road Safety)", "slug": "tn-innuyir-kappom", "state": "Tamil Nadu", "category": ["Road Safety", "Insurance"], "ministry": "Tamil Nadu Transport", "benefits": "Rs. 1 lakh accident relief + free trauma care for road accident victims", "description": "Road safety and accident victim compensation scheme with free emergency care.", "source_url": "https://www.tn.gov.in", "source_type": "html"},
    {"name": "TN Cradle Baby Scheme", "slug": "tn-cradle-baby", "state": "Tamil Nadu", "category": ["Children", "Adoption", "Girl Child"], "ministry": "Tamil Nadu Social Welfare", "benefits": "Safe cradle facilities at hospitals to prevent female infanticide", "description": "Programme to prevent female infanticide by providing safe baby surrender options.", "source_url": "https://www.tnsocialwelfare.tn.gov.in", "source_type": "html"},
    {"name": "TN Chief Minister's Special Fellowship", "slug": "tn-cm-special-fellowship", "state": "Tamil Nadu", "category": ["Education", "Research", "Fellowship"], "ministry": "Tamil Nadu Higher Education", "benefits": "Rs. 20,000 per month fellowship for doctoral research in priority areas", "description": "Research fellowship for Ph.D scholars working on issues relevant to Tamil Nadu development.", "source_url": "https://www.tn.gov.in", "source_type": "html"},

    # ═══════════ CENTRAL — FOOD & PUBLIC DISTRIBUTION ═══════════
    {"name": "National Food Security Act (NFSA)", "slug": "nfsa", "state": "Central", "category": ["Food", "BPL", "PDS"], "ministry": "Ministry of Consumer Affairs", "benefits": "5 kg foodgrain per person/month at Rs. 1-3/kg for 81.34 crore persons", "description": "Legal entitlement to subsidized foodgrains through PDS for priority and Antyodaya households.", "source_url": "https://dfpd.gov.in", "source_type": "portal"},
    {"name": "Antyodaya Anna Yojana", "slug": "antyodaya-anna-yojana", "state": "Central", "category": ["Food", "Poorest", "BPL"], "ministry": "Ministry of Consumer Affairs", "benefits": "35 kg foodgrain per family per month at Rs. 2 (wheat) and Rs. 3 (rice)", "description": "Highly subsidized foodgrain for the poorest of the poor families identified under NFSA.", "source_url": "https://dfpd.gov.in", "source_type": "portal"},
    {"name": "One Nation One Ration Card", "slug": "onorc", "state": "Central", "category": ["Food", "PDS", "Portability"], "ministry": "Ministry of Consumer Affairs", "benefits": "Ration card portability allowing purchase of foodgrain from any fair price shop nationwide", "description": "Enables migrant workers and their families to access PDS benefits from any FPS in the country.", "source_url": "https://dfpd.gov.in", "source_type": "portal"},

    # ═══════════ CENTRAL — TRANSPORT & INFRASTRUCTURE ═══════════
    {"name": "PM E-Bus Sewa Scheme", "slug": "pm-e-bus-sewa", "state": "Central", "category": ["Transport", "Electric", "Urban"], "ministry": "Ministry of Housing", "benefits": "10,000 electric buses across 169 cities with central subsidy", "description": "Deployment of electric buses in cities and inter-city routes with central financial support.", "source_url": "https://mohua.gov.in", "source_type": "html"},
    {"name": "FAME India (Electric Vehicles)", "slug": "fame-india", "state": "Central", "category": ["Transport", "Electric", "Subsidy"], "ministry": "Ministry of Heavy Industries", "benefits": "Subsidy of Rs. 15,000-1,50,000 on purchase of electric vehicles", "description": "Faster Adoption and Manufacturing of Electric Vehicles through demand incentives and charging infrastructure.", "source_url": "https://fame2.heavyindustries.gov.in", "source_type": "portal"},
    {"name": "PM Gati Shakti National Master Plan", "slug": "pm-gati-shakti", "state": "Central", "category": ["Infrastructure", "Logistics", "Digital"], "ministry": "DPIIT", "benefits": "Integrated infrastructure planning across 16 ministries for seamless multimodal connectivity", "description": "Digital platform for integrated planning of infrastructure to reduce logistics costs.", "source_url": "https://pmgatishakti.gov.in", "source_type": "portal"},

    # ═══════════ CENTRAL — ENERGY & ENVIRONMENT ═══════════
    {"name": "PM Surya Ghar Muft Bijli Yojana", "slug": "pm-surya-ghar", "state": "Central", "category": ["Solar", "Electricity", "Subsidy"], "ministry": "Ministry of New & Renewable Energy", "benefits": "Free rooftop solar installation with subsidy up to Rs. 78,000 for households", "description": "Rooftop solar scheme providing 300 units free electricity per month through solar panels.", "source_url": "https://pmsuryaghar.gov.in", "source_type": "portal"},
    {"name": "PM Kusum (Solar for Farmers)", "slug": "pm-kusum", "state": "Central", "category": ["Solar", "Agriculture", "Pump"], "ministry": "Ministry of New & Renewable Energy", "benefits": "60% subsidy on solar pump sets for farmers, sell surplus power to grid", "description": "Solar energy for farmers through standalone solar pumps and grid-connected solar power plants.", "source_url": "https://pmkusum.mnre.gov.in", "source_type": "portal"},
    {"name": "National Clean Air Programme", "slug": "ncap", "state": "Central", "category": ["Environment", "Air Quality"], "ministry": "Ministry of Environment", "benefits": "20-30% reduction in PM2.5 and PM10 concentrations in 131 cities", "description": "National strategy to reduce air pollution levels in cities through targeted action plans.", "source_url": "https://moef.gov.in", "source_type": "html"},
    {"name": "Namami Gange Programme", "slug": "namami-gange", "state": "Central", "category": ["Environment", "River", "Water"], "ministry": "Jal Shakti Ministry", "benefits": "Sewage treatment plants, river surface cleaning, afforestation along Ganga basin", "description": "Comprehensive programme for conservation, rejuvenation, and cleaning of the river Ganga.", "source_url": "https://nmcg.nic.in", "source_type": "portal"},
    {"name": "Green India Mission", "slug": "green-india-mission", "state": "Central", "category": ["Environment", "Forest", "Climate"], "ministry": "Ministry of Environment", "benefits": "10 million hectares afforestation and improving quality of existing forests", "description": "National mission for enhanced forest cover and ecosystem services to combat climate change.", "source_url": "https://moef.gov.in", "source_type": "html"},

    # ═══════════ CENTRAL — RURAL DEVELOPMENT ═══════════
    {"name": "Shyama Prasad Mukherji Rurban Mission", "slug": "spmrm-rurban", "state": "Central", "category": ["Rural", "Urban", "Development"], "ministry": "Ministry of Rural Development", "benefits": "Rs. 5-8 crore per cluster for rural-urban transformation with smart infrastructure", "description": "Aims to stimulate local economic development in rural areas with urban amenities.", "source_url": "https://rurban.gov.in", "source_type": "portal"},
    {"name": "Saansad Adarsh Gram Yojana", "slug": "sagy", "state": "Central", "category": ["Rural", "Village", "Development"], "ministry": "Ministry of Rural Development", "benefits": "Model village development by MP adoption with holistic infrastructure and social development", "description": "MPs adopt villages and develop them as model villages with improved infrastructure and governance.", "source_url": "https://saanjhi.gov.in", "source_type": "portal"},
    {"name": "Pradhan Mantri Adarsh Gram Yojana", "slug": "pmagy", "state": "Central", "category": ["Rural", "SC", "Development"], "ministry": "Ministry of Social Justice", "benefits": "Rs. 20 lakh per village for integrated development of SC majority villages", "description": "Integrated development of villages with 50%+ SC population through convergent planning.", "source_url": "https://socialjustice.gov.in", "source_type": "html"},

    # ═══════════ CENTRAL — SCIENCE & TECHNOLOGY ═══════════
    {"name": "INSPIRE Fellowship", "slug": "inspire-fellowship", "state": "Central", "category": ["Education", "Research", "Science"], "ministry": "Ministry of Science", "benefits": "Rs. 80,000/month fellowship for Ph.D in natural and basic sciences", "description": "Fellowship to attract talent to research careers in basic and applied sciences.", "source_url": "https://online-inspire.gov.in", "source_type": "portal"},
    {"name": "Atal Innovation Mission (AIM)", "slug": "atal-innovation-mission", "state": "Central", "category": ["Innovation", "Startup", "Youth"], "ministry": "NITI Aayog", "benefits": "Atal Tinkering Labs (Rs. 20 lakh per school) + Atal Incubation Centres (Rs. 10 crore)", "description": "Promotes culture of innovation through tinkering labs in schools and incubation support for startups.", "source_url": "https://aim.gov.in", "source_type": "portal"},
    {"name": "National Super Computing Mission", "slug": "nsm", "state": "Central", "category": ["Technology", "Computing", "Research"], "ministry": "MeitY", "benefits": "Access to 73+ petaflops high-performance computing for researchers and industry", "description": "Building a network of supercomputers to meet growing computational demands of academia and industry.", "source_url": "https://nsm.gov.in", "source_type": "portal"},

    # ═══════════ CENTRAL — DEFENCE & VETERAN ═══════════
    {"name": "AGNIPATH Scheme", "slug": "agnipath-scheme", "state": "Central", "category": ["Defence", "Youth", "Employment"], "ministry": "Ministry of Defence", "benefits": "4-year military service + Rs. 11.71 lakh Seva Nidhi package on exit + skill certificate", "description": "Short-tenure military recruitment programme for youth aged 17.5-21 across all three services.", "source_url": "https://www.mod.gov.in", "source_type": "html"},
    {"name": "Ex-Servicemen Contributory Health Scheme", "slug": "echs", "state": "Central", "category": ["Health", "Defence", "Veteran"], "ministry": "Ministry of Defence", "benefits": "Cashless medical treatment for ex-servicemen and dependents at 430+ polyclinics", "description": "Comprehensive healthcare for ex-servicemen and their dependents through dedicated polyclinics.", "source_url": "https://echs.gov.in", "source_type": "portal"},

    # ═══════════ CENTRAL — LESSER KNOWN SCHEMES ═══════════
    {"name": "PM Matsya Sampada Yojana", "slug": "pmmsy", "state": "Central", "category": ["Fisheries", "Blue Revolution"], "ministry": "Ministry of Fisheries", "benefits": "40-60% subsidy for fishing boats, cold storage, processing units", "description": "Blue Revolution scheme to develop sustainable fisheries sector and double fishermen income.", "source_url": "https://pmmsy.dof.gov.in", "source_type": "portal"},
    {"name": "National Bamboo Mission", "slug": "national-bamboo-mission", "state": "Central", "category": ["Agriculture", "Bamboo", "Livelihood"], "ministry": "Ministry of Agriculture", "benefits": "Subsidy for bamboo plantation, processing, value addition, and marketing", "description": "Promotes bamboo sector through plantation, processing, and market development.", "source_url": "https://nbm.nic.in", "source_type": "portal"},
    {"name": "PM Formalisation of Micro Food Processing", "slug": "pm-fme", "state": "Central", "category": ["Food Processing", "MSME", "Subsidy"], "ministry": "Ministry of Food Processing", "benefits": "Rs. 10 lakh subsidy (35% of project cost) for upgrading micro food processing units", "description": "Supports micro food processing enterprises with credit-linked subsidy for technology upgradation.", "source_url": "https://pmfme.mofpi.gov.in", "source_type": "portal"},
    {"name": "Pradhan Mantri Khanij Kshetra Kalyan Yojana", "slug": "pmkkky", "state": "Central", "category": ["Mining", "Tribal", "Development"], "ministry": "Ministry of Mines", "benefits": "60% of District Mineral Foundation for mining-affected area development", "description": "Welfare of mining-affected communities through development projects funded by mining royalties.", "source_url": "https://mines.gov.in", "source_type": "html"},
    {"name": "National AYUSH Mission", "slug": "national-ayush-mission", "state": "Central", "category": ["Health", "Ayurveda", "Traditional"], "ministry": "Ministry of AYUSH", "benefits": "Free AYUSH healthcare services, herbal gardens, and traditional medicine promotion", "description": "Promotes AYUSH systems (Ayurveda, Yoga, Unani, Siddha, Homeopathy) through infrastructure and education.", "source_url": "https://namayush.gov.in", "source_type": "portal"},
    {"name": "PM Aadi Adarsh Gram Yojana", "slug": "pmaagy", "state": "Central", "category": ["Tribal", "Village", "Development"], "ministry": "Ministry of Tribal Affairs", "benefits": "Rs. 20.38 lakh gap-fill funding per village for 36,428 tribal villages", "description": "Integrated development of tribal-majority villages with roads, schools, health centres, and connectivity.", "source_url": "https://tribal.nic.in", "source_type": "html"},
    {"name": "Eklavya Model Residential Schools", "slug": "emrs", "state": "Central", "category": ["Education", "Tribal", "Residential"], "ministry": "Ministry of Tribal Affairs", "benefits": "Free residential education with boarding for ST students from Class 6-12", "description": "Quality residential schools in tribal areas on par with Navodaya Vidyalayas for tribal students.", "source_url": "https://emrs.tribal.gov.in", "source_type": "portal"},
    {"name": "Van Dhan Vikas Yojana", "slug": "van-dhan-vikas", "state": "Central", "category": ["Tribal", "Forest Produce", "Livelihood"], "ministry": "Ministry of Tribal Affairs", "benefits": "Rs. 15 lakh per SHG cluster for minor forest produce value addition and marketing", "description": "Supports tribal communities in value addition and marketing of minor forest produce through Van Dhan centres.", "source_url": "https://trifed.tribal.gov.in", "source_type": "portal"},
    {"name": "Pradhan Mantri Annadata Aay Sanrakshan Abhiyan", "slug": "pm-aasha", "state": "Central", "category": ["Agriculture", "MSP", "Procurement"], "ministry": "Ministry of Agriculture", "benefits": "Government procurement at MSP + deficiency payment + private procurement with insurance", "description": "Ensures MSP to farmers through modified procurement, deficiency payment, and private participation.", "source_url": "https://agricoop.nic.in", "source_type": "html"},
    {"name": "Interest Subvention Scheme for Agriculture", "slug": "interest-subvention-agri", "state": "Central", "category": ["Agriculture", "Loan", "Interest"], "ministry": "Ministry of Agriculture", "benefits": "Crop loans up to Rs. 3 lakh at 4% interest (7% with 3% subvention for prompt repayment)", "description": "Interest subsidy on short-term crop loans to make agricultural credit affordable.", "source_url": "https://agricoop.nic.in", "source_type": "html"},
    {"name": "National Livestock Mission", "slug": "national-livestock-mission", "state": "Central", "category": ["Animal Husbandry", "Poultry", "Livestock"], "ministry": "Ministry of Fisheries", "benefits": "Subsidies for poultry, goat, pig, and rabbit farming entrepreneurship", "description": "Promotes sustainable livestock development through breed improvement, feed, and entrepreneurship.", "source_url": "https://dahd.nic.in", "source_type": "html"},
    {"name": "Rashtriya Gokul Mission", "slug": "rashtriya-gokul-mission", "state": "Central", "category": ["Animal Husbandry", "Cattle", "Dairy"], "ministry": "Ministry of Fisheries", "benefits": "AI breeding, Gokul Grams, breed multiplication farms for indigenous cattle", "description": "Conservation and development of indigenous bovine breeds through scientific breeding.", "source_url": "https://dahd.nic.in", "source_type": "html"},
    {"name": "PM Kisan Maan Dhan Yojana", "slug": "pm-kisan-maan-dhan", "state": "Central", "category": ["Pension", "Farmers"], "ministry": "Ministry of Agriculture", "benefits": "Rs. 3,000 per month pension after age 60 for small/marginal farmers", "description": "Voluntary pension scheme for small and marginal farmers with monthly contribution of Rs. 55-200.", "source_url": "https://pmkmy.gov.in", "source_type": "portal"},
    {"name": "PM Shram Yogi Maan Dhan", "slug": "pm-sym", "state": "Central", "category": ["Pension", "Unorganized", "Labour"], "ministry": "Ministry of Labour", "benefits": "Rs. 3,000 per month pension after 60 for unorganized workers with contribution Rs. 55-200/month", "description": "Voluntary pension scheme for unorganized workers like street vendors, rickshaw pullers, domestic workers.", "source_url": "https://labour.gov.in", "source_type": "html"},
    {"name": "PM Laghu Vyapari Maan Dhan", "slug": "pm-laghu-vyapari", "state": "Central", "category": ["Pension", "Traders", "Business"], "ministry": "Ministry of Labour", "benefits": "Rs. 3,000 per month pension after 60 for small traders with annual turnover < Rs. 1.5 crore", "description": "Voluntary pension scheme for small traders and self-employed with GST turnover less than Rs. 1.5 crore.", "source_url": "https://labour.gov.in", "source_type": "html"},
    {"name": "Nari Shakti Puraskar", "slug": "nari-shakti-puraskar", "state": "Central", "category": ["Women", "Award", "Empowerment"], "ministry": "Ministry of WCD", "benefits": "Rs. 2 lakh cash award + certificate for women contributing to society", "description": "National award recognizing exceptional contribution of women in various fields.", "source_url": "https://wcd.nic.in", "source_type": "html"},
    {"name": "Integrated Child Protection Scheme", "slug": "icps", "state": "Central", "category": ["Children", "Protection", "Welfare"], "ministry": "Ministry of WCD", "benefits": "Child protection services, juvenile justice homes, sponsorship for vulnerable children", "description": "Centralised system for child protection including childline 1098, foster care, and institutional care.", "source_url": "https://wcd.nic.in", "source_type": "html"},
    {"name": "National Creche Scheme", "slug": "national-creche-scheme", "state": "Central", "category": ["Children", "Women", "Daycare"], "ministry": "Ministry of WCD", "benefits": "Free daycare for children 0-6 years of working mothers with nutrition and health check", "description": "Provides daycare facilities for children of working mothers in rural and urban areas.", "source_url": "https://wcd.nic.in", "source_type": "html"},
    {"name": "PM DAKSH (Skill for SC)", "slug": "pm-daksh", "state": "Central", "category": ["Skills", "SC", "Training"], "ministry": "Ministry of Social Justice", "benefits": "Free skill training in 83+ job roles + placement support for SC/OBC youth", "description": "Skill development scheme targeting SC, OBC, EBC, DNT, and safai karamchari youth.", "source_url": "https://pmdaksh.dosje.gov.in", "source_type": "portal"},
    {"name": "Swadhar Greh (Shelter for Women)", "slug": "swadhar-greh", "state": "Central", "category": ["Women", "Shelter", "Rehabilitation"], "ministry": "Ministry of WCD", "benefits": "Shelter, food, clothing, medical treatment, legal aid, and rehabilitation for women in distress", "description": "Institutional support for women in difficult circumstances including destitute widows and rescued victims.", "source_url": "https://wcd.nic.in", "source_type": "html"},
    {"name": "Pradhan Mantri Vaya Vandana Yojana", "slug": "pmvvy", "state": "Central", "category": ["Pension", "Elderly", "Insurance"], "ministry": "Ministry of Finance", "benefits": "Guaranteed pension of Rs. 1,000-10,000/month at 7.4% for senior citizens (60+)", "description": "Guaranteed pension scheme for senior citizens operated by LIC with investment up to Rs. 15 lakh.", "source_url": "https://licindia.in", "source_type": "portal"},

    # ═══════════ CENTRAL — DIGITAL & GOVERNANCE ═══════════
    {"name": "Unified Mobile Application for New-age Governance (UMANG)", "slug": "umang", "state": "Central", "category": ["Digital", "Governance", "Mobile"], "ministry": "MeitY", "benefits": "Access to 1,800+ government services from 300+ departments via single mobile app", "description": "Unified mobile app providing access to central and state government services on mobile.", "source_url": "https://web.umang.gov.in", "source_type": "portal"},
    {"name": "PM WANI (Public WiFi)", "slug": "pm-wani", "state": "Central", "category": ["Digital", "Internet", "WiFi"], "ministry": "DoT", "benefits": "Free/affordable public WiFi hotspots through small entrepreneurs across India", "description": "Public WiFi access through small businesses as Public Data Office aggregators.", "source_url": "https://dot.gov.in", "source_type": "html"},
    {"name": "Common Service Centre (CSC)", "slug": "csc", "state": "Central", "category": ["Digital", "Services", "Rural"], "ministry": "MeitY", "benefits": "Government services, banking, insurance, bill payment at village level through CSC", "description": "Network of 5 lakh CSCs providing e-governance services to rural citizens.", "source_url": "https://csc.gov.in", "source_type": "portal"},
    {"name": "GeM (Government e-Marketplace)", "slug": "gem", "state": "Central", "category": ["Business", "Procurement", "Digital"], "ministry": "Ministry of Commerce", "benefits": "MSMEs and startups can sell products/services directly to government departments", "description": "Online marketplace for government procurement enabling direct seller-buyer interface.", "source_url": "https://gem.gov.in", "source_type": "portal"},

    # ═══════════ CENTRAL — URBAN & SMART CITY ═══════════
    {"name": "Smart Cities Mission", "slug": "smart-cities-mission", "state": "Central", "category": ["Urban", "Smart City", "Infrastructure"], "ministry": "Ministry of Housing", "benefits": "Rs. 500 crore per city for smart infrastructure in 100 selected cities", "description": "Urban renewal programme to develop 100 cities with smart infrastructure and citizen services.", "source_url": "https://smartcities.gov.in", "source_type": "portal"},
    {"name": "AMRUT (Urban Infrastructure)", "slug": "amrut", "state": "Central", "category": ["Urban", "Water", "Infrastructure"], "ministry": "Ministry of Housing", "benefits": "Water supply, sewerage, urban transport, green spaces in 500 cities", "description": "Urban infrastructure development focusing on water supply, sewerage, and storm water drainage.", "source_url": "https://amrut.gov.in", "source_type": "portal"},
    {"name": "PM Urban Employment Guarantee", "slug": "pm-ueg", "state": "Central", "category": ["Employment", "Urban", "Guarantee"], "ministry": "Ministry of Housing", "benefits": "100 days guaranteed wage employment for urban poor similar to MGNREGA", "description": "Urban employment guarantee programme providing work in areas like sanitation, urban forestry.", "source_url": "https://mohua.gov.in", "source_type": "html"},
    {"name": "Deendayal Antyodaya Yojana - NULM", "slug": "day-nulm", "state": "Central", "category": ["Urban", "Livelihood", "SHG"], "ministry": "Ministry of Housing", "benefits": "Interest subsidy on loans up to Rs. 10 lakh + SHG formation + shelter for urban homeless", "description": "Urban poverty alleviation through skill training, entrepreneurship, and self-help groups.", "source_url": "https://nulm.gov.in", "source_type": "portal"},

    # ═══════════ OTHER STATES — EXPANDED ═══════════
    {"name": "West Bengal Kanyashree Prakalpa", "slug": "wb-kanyashree", "state": "West Bengal", "category": ["Girl Child", "Education", "Cash Transfer"], "ministry": "West Bengal Government", "benefits": "Rs. 750/year for 13-18 girl students + Rs. 25,000 on turning 18 if unmarried", "description": "Cash transfer to keep girls in school and prevent child marriage.", "source_url": "https://wbkanyashree.gov.in", "source_type": "portal"},
    {"name": "West Bengal Swasthya Sathi", "slug": "wb-swasthya-sathi", "state": "West Bengal", "category": ["Health", "Insurance"], "ministry": "West Bengal Government", "benefits": "Rs. 5 lakh health cover per family per year for all families in WB", "description": "Universal health insurance for all families in West Bengal.", "source_url": "https://swasthyasathi.gov.in", "source_type": "portal"},
    {"name": "Odisha KALIA Scheme", "slug": "odisha-kalia", "state": "Odisha", "category": ["Agriculture", "Farmers", "Income Support"], "ministry": "Odisha Government", "benefits": "Rs. 10,000/year for small farmers + Rs. 12,500 for landless agricultural workers", "description": "Income support for farmers and landless labourers in Odisha.", "source_url": "https://kalia.odisha.gov.in", "source_type": "portal"},
    {"name": "Telangana Rythu Bandhu", "slug": "telangana-rythu-bandhu", "state": "Telangana", "category": ["Agriculture", "Farmers", "Cash Transfer"], "ministry": "Telangana Government", "benefits": "Rs. 10,000 per acre per year for all farmers (both seasons)", "description": "Investment support for farmers at start of each crop season.", "source_url": "https://rythubandhu.telangana.gov.in", "source_type": "portal"},
    {"name": "Telangana Kalyana Lakshmi", "slug": "telangana-kalyana-lakshmi", "state": "Telangana", "category": ["Marriage", "Women", "BPL"], "ministry": "Telangana Government", "benefits": "Rs. 1,00,116 marriage assistance for BPL girls", "description": "Marriage financial assistance for girls from economically weaker families.", "source_url": "https://telanganaepass.cgg.gov.in", "source_type": "portal"},
    {"name": "Bihar Student Credit Card", "slug": "bihar-student-credit-card", "state": "Bihar", "category": ["Education", "Loan", "Youth"], "ministry": "Bihar Government", "benefits": "Education loan up to Rs. 4 lakh at zero interest for higher education", "description": "Interest-free education loan for Bihar students for higher education.", "source_url": "https://www.7nishchay-yuvaupmission.bihar.gov.in", "source_type": "portal"},
    {"name": "Gujarat Vahali Dikri Yojana", "slug": "gujarat-vahali-dikri", "state": "Gujarat", "category": ["Girl Child", "Education", "Cash Transfer"], "ministry": "Gujarat Government", "benefits": "Rs. 4,000 (Class 1) + Rs. 6,000 (Class 9) + Rs. 1,00,000 (at 18 years)", "description": "Financial assistance for girl children at key milestones to promote female education.", "source_url": "https://wcd.gujarat.gov.in", "source_type": "portal"},
    {"name": "MP Ladli Laxmi Yojana", "slug": "mp-ladli-laxmi", "state": "Madhya Pradesh", "category": ["Girl Child", "Education", "Insurance"], "ministry": "MP Government", "benefits": "Rs. 1,18,000 in stages from birth to marriage + scholarship for education", "description": "Multi-stage financial support for girl children from birth through education to marriage.", "source_url": "https://ladlilaxmi.mp.gov.in", "source_type": "portal"},
    {"name": "Chhattisgarh Rajiv Gandhi Kisan Nyay", "slug": "cg-rajiv-gandhi-kisan-nyay", "state": "Chhattisgarh", "category": ["Agriculture", "Farmers", "Input Support"], "ministry": "Chhattisgarh Government", "benefits": "Rs. 9,000-13,000 per acre input support for paddy, maize, sugarcane farmers", "description": "Direct input support to farmers based on crop area registered.", "source_url": "https://rgkny.cg.nic.in", "source_type": "portal"},
    {"name": "Punjab Aashirwad Scheme", "slug": "punjab-aashirwad", "state": "Punjab", "category": ["Marriage", "Women", "BPL"], "ministry": "Punjab Government", "benefits": "Rs. 21,000 marriage assistance for SC/BC/Minority girls", "description": "Financial assistance for marriage of daughters from poor families.", "source_url": "https://punjab.gov.in", "source_type": "html"},
    {"name": "Jharkhand MMVY", "slug": "jharkhand-mmvy", "state": "Jharkhand", "category": ["Girl Child", "Education"], "ministry": "Jharkhand Government", "benefits": "Rs. 2,500-5,000 per year for girl students from Class 1 to Post Graduation", "description": "Scholarship for girl students at various education levels.", "source_url": "https://www.jharkhand.gov.in", "source_type": "html"},

    # ═══════════ LESSER KNOWN — NICHE SCHEMES ═══════════
    {"name": "Pradhan Mantri Gram Parivahan Yojana", "slug": "pmgpy", "state": "Central", "category": ["Transport", "Rural", "Subsidy"], "ministry": "Ministry of Rural Development", "benefits": "Interest subsidy on purchase of small passenger transport vehicles for rural areas", "description": "Supports rural entrepreneurs to start passenger transport services in remote areas.", "source_url": "https://prd.nic.in", "source_type": "html"},
    {"name": "Scheme for Trans-Disciplinary Research", "slug": "imprint-2", "state": "Central", "category": ["Research", "Innovation", "Higher Education"], "ministry": "Ministry of Education", "benefits": "Research funding of Rs. 50 lakh - Rs. 5 crore for trans-disciplinary research projects", "description": "Research funding for projects addressing India's engineering challenges.", "source_url": "https://imprint-india.org", "source_type": "portal"},
    {"name": "Unnat Bharat Abhiyan", "slug": "unnat-bharat-abhiyan", "state": "Central", "category": ["Rural", "Education", "Development"], "ministry": "Ministry of Education", "benefits": "Higher education institutions adopt villages for technology-based development", "description": "Links premier higher education institutions with rural communities for sustainable development.", "source_url": "https://unnatbharatabhiyan.gov.in", "source_type": "portal"},
    {"name": "National Career Service Portal", "slug": "ncs-portal", "state": "Central", "category": ["Employment", "Job", "Services"], "ministry": "Ministry of Labour", "benefits": "Free job matching, career counselling, vocational guidance, job fairs across India", "description": "One-stop portal for employment services including job matching and career counselling.", "source_url": "https://www.ncs.gov.in", "source_type": "portal"},
    {"name": "PM SHRI Schools", "slug": "pm-shri-schools", "state": "Central", "category": ["Education", "School", "NEP"], "ministry": "Ministry of Education", "benefits": "14,500 PM SHRI schools upgraded with modern labs, smart classrooms, sports facilities", "description": "Model schools implementing National Education Policy with state-of-the-art facilities.", "source_url": "https://pmshri.education.gov.in", "source_type": "portal"},
    {"name": "Samagra Puraskar for Best Schools", "slug": "samagra-puraskar", "state": "Central", "category": ["Education", "Award", "School"], "ministry": "Ministry of Education", "benefits": "Cash awards for best performing schools in different categories", "description": "National school awards recognizing excellence in education quality and innovation.", "source_url": "https://samagra.education.gov.in", "source_type": "portal"},
    {"name": "NIPUN Bharat (Foundational Literacy)", "slug": "nipun-bharat", "state": "Central", "category": ["Education", "Literacy", "Children"], "ministry": "Ministry of Education", "benefits": "Foundational literacy and numeracy for all children by end of Class 3", "description": "National initiative for ensuring foundational reading writing and numeracy skills by grade 3.", "source_url": "https://nipunbharat.education.gov.in", "source_type": "portal"},
    {"name": "Khelo India Sports Programme", "slug": "khelo-india", "state": "Central", "category": ["Sports", "Youth", "Training"], "ministry": "Ministry of Sports", "benefits": "Rs. 5 lakh/year scholarship for 1,000 talented young athletes + training + competition", "description": "Identifies and nurtures sporting talent through grassroots competitions and scholarships.", "source_url": "https://kheloindia.gov.in", "source_type": "portal"},
    {"name": "Fit India Movement", "slug": "fit-india", "state": "Central", "category": ["Sports", "Health", "Fitness"], "ministry": "Ministry of Sports", "benefits": "Free fitness assessment, school fitness programmes, community fitness activities", "description": "National movement to encourage physical fitness and healthy lifestyle.", "source_url": "https://fitindia.gov.in", "source_type": "portal"},
    {"name": "Rashtriya Vayoshri Yojana", "slug": "rvy", "state": "Central", "category": ["Elderly", "Disability", "BPL"], "ministry": "Ministry of Social Justice", "benefits": "Free physical aids (spectacles, hearing aids, walkers, crutches) for BPL senior citizens", "description": "Distribution of physical assistive devices to BPL senior citizens with age-related disabilities.", "source_url": "https://socialjustice.gov.in", "source_type": "html"},
    {"name": "SANKALP Skill Programme", "slug": "sankalp", "state": "Central", "category": ["Skills", "Youth", "District"], "ministry": "Ministry of Skill Development", "benefits": "District-level skill training ecosystem with industry partnership and placement", "description": "Skills Acquisition and Knowledge Awareness for Livelihood Promotion strengthening district skill ecosystem.", "source_url": "https://msde.gov.in", "source_type": "html"},
    {"name": "National Education Policy Digital University", "slug": "nep-digital-university", "state": "Central", "category": ["Education", "Digital", "University"], "ministry": "Ministry of Education", "benefits": "Free/affordable online degree programmes from top universities through digital platform", "description": "Digital university offering world-class online degrees as per National Education Policy 2020.", "source_url": "https://www.education.gov.in", "source_type": "html"},

    # ═══════════ TAMIL NADU — EDUCATION & SCHOLARSHIP (DETAILED) ═══════════
    {"name": "TN BC/MBC Post-Matric Scholarship", "slug": "tn-bc-mbc-post-matric-scholarship", "state": "Tamil Nadu", "category": ["Education", "Scholarship", "BC", "MBC", "Diploma", "Polytechnic"], "ministry": "BC/MBC Welfare Department, Tamil Nadu", "benefits": "Full tuition fee reimbursement + maintenance allowance of Rs. 400-1,200/month + book allowance for BC/MBC/DNC students pursuing post-matric education including polytechnic diploma, degree, and professional courses", "description": "Post-matric scholarship for Backward Classes (BC), Most Backward Classes (MBC), and De-notified Communities (DNC) students in Tamil Nadu. Covers polytechnic diploma, ITI, degree, engineering, medical, and professional courses. Eligibility: Family annual income must be below Rs. 2,00,000 (Rs. 2 lakhs). Student must have passed 10th/12th from a recognized institution. Must be a native of Tamil Nadu. Apply through TN e-Scholarship portal. Documents needed: Community certificate (BC/MBC/DNC), income certificate (below 2 lakhs), previous mark sheets, Aadhaar card, bank passbook, institution bonafide certificate.", "source_url": "https://escholarship.tn.gov.in", "source_type": "portal", "eligibility": "BC/MBC/DNC category, Family income below Rs. 2,00,000/year, Tamil Nadu native, Passed 10th/12th", "documents_required": "Community certificate, Income certificate, Mark sheets, Aadhaar, Bank passbook, Bonafide certificate", "application_mode": "Online via https://escholarship.tn.gov.in"},

    {"name": "TN SC/ST Post-Matric Scholarship", "slug": "tn-sc-st-post-matric-scholarship", "state": "Tamil Nadu", "category": ["Education", "Scholarship", "SC", "ST", "Diploma", "Polytechnic"], "ministry": "Adi Dravidar & Tribal Welfare Department, Tamil Nadu", "benefits": "Full tuition fees + examination fees + maintenance allowance Rs. 550-1,200/month + book allowance + thesis typing charges for SC/ST students in post-matric education including polytechnic, diploma, degree, engineering, medical courses", "description": "Post-matric scholarship for Scheduled Caste (SC) and Scheduled Tribe (ST) students in Tamil Nadu. Covers all post-matric courses: polytechnic diploma, ITI, UG degree, PG, engineering, medical, law, MBA, MCA, PhD. Eligibility: SC/ST community, Family annual income should be below Rs. 2,50,000 (Rs. 2.5 lakhs). No income limit for SC/ST students in some years — check current notification. Must be studying in recognized institution in Tamil Nadu. Apply through TN e-Scholarship portal or Adi Dravidar Welfare Department office. Documents needed: Community certificate (SC/ST), income certificate, Aadhaar, bank account, mark sheets, bonafide.", "source_url": "https://escholarship.tn.gov.in", "source_type": "portal", "eligibility": "SC/ST category, Family income below Rs. 2,50,000/year, Tamil Nadu native", "documents_required": "Community certificate (SC/ST), Income certificate, Aadhaar, Bank passbook, Mark sheets, Bonafide certificate", "application_mode": "Online via https://escholarship.tn.gov.in"},

    {"name": "TN Government Polytechnic Free Education", "slug": "tn-govt-polytechnic-free-education", "state": "Tamil Nadu", "category": ["Education", "Polytechnic", "Diploma", "Free", "CSE", "Engineering"], "ministry": "Department of Technical Education, Tamil Nadu", "benefits": "Completely free education (zero tuition fees) at all government polytechnic colleges in Tamil Nadu for diploma courses including Computer Science Engineering (CSE), Mechanical, Electrical, Civil, ECE, and all branches. Free for BC/MBC/SC/ST students. Additional benefits: free bus pass, eligible for scholarship stipends", "description": "Tamil Nadu government polytechnic colleges offer free diploma education for students from BC, MBC, SC, ST, and economically weaker sections. All government polytechnic colleges in TN provide tuition-free diploma courses in branches like Computer Science & Engineering (CSE), Mechanical, Electrical, Civil, ECE, EEE, Auto, etc. Admission through TNEA (Tamil Nadu Engineering Admissions) counselling based on 10th marks or SSLC marks. Students are also eligible for monthly stipend through scholarship schemes. Government polytechnic hostels are available at subsidized rates. Apply through TNDTE (Directorate of Technical Education) online portal for diploma admissions.", "source_url": "https://www.tndte.gov.in", "source_type": "portal", "eligibility": "Passed 10th (SSLC), Tamil Nadu native, Admission via TNEA counselling", "documents_required": "10th mark sheet, Community certificate, Transfer certificate, Aadhaar, Photos", "application_mode": "Online via https://www.tndte.gov.in"},

    {"name": "Central Sector Scheme of Scholarship for College and University Students", "slug": "central-sector-scholarship-college", "state": "Central", "category": ["Education", "Scholarship", "Merit", "Diploma", "Degree"], "ministry": "Ministry of Education", "benefits": "Rs. 10,000 per year for degree students and Rs. 20,000 per year for PG students from economically weaker families. For diploma/polytechnic students: Rs. 10,000/year. Top 20% meritorious students with family income below Rs. 4.5 lakhs/year qualify. Given for 3 years for degree, 2 years for diploma courses", "description": "Merit-based central scholarship for students who scored in top 20% of their board exam (10th/12th). Family annual income must be below Rs. 4,50,000 (Rs. 4.5 lakhs). Applicable to students pursuing regular courses in colleges, polytechnics, and universities. Not linked to caste/community — open to General, OBC, SC, ST categories. Apply through National Scholarship Portal (NSP). Documents: 10th/12th marksheet, family income certificate, Aadhaar, bank account.", "source_url": "https://scholarships.gov.in", "source_type": "portal", "eligibility": "Top 20% in board exam, Family income below Rs. 4,50,000/year, Any category", "documents_required": "Board mark sheets, Income certificate, Aadhaar, Bank passbook", "application_mode": "Online via https://scholarships.gov.in (National Scholarship Portal)"},

    {"name": "TN Chief Minister's Merit Scholarship", "slug": "tn-cm-merit-scholarship", "state": "Tamil Nadu", "category": ["Education", "Scholarship", "Merit", "Polytechnic", "Engineering"], "ministry": "Tamil Nadu Higher Education Department", "benefits": "Rs. 500-1,000 per month merit scholarship for top-scoring diploma and engineering students in government institutions. Additional gold medals and cash prizes for university rank holders.", "description": "Tamil Nadu Chief Minister's merit-based scholarship for students who achieve high marks (above 90%) in polytechnic diploma and engineering courses at government colleges. Students scoring above 97% in polytechnic diploma are eligible for enhanced merit scholarship. This is applicable to all categories (General, BC, MBC, SC, ST). Apply through the institution — scholarship is disbursed through the college.", "source_url": "https://www.tn.gov.in", "source_type": "html", "eligibility": "High marks (90%+ in diploma/engineering), Government college student, Tamil Nadu native", "documents_required": "Mark sheets, College bonafide, Aadhaar, Bank passbook", "application_mode": "Through institution"},

    {"name": "AICTE Pragati & Saksham Scholarship", "slug": "aicte-pragati-saksham", "state": "Central", "category": ["Education", "Scholarship", "Women", "Disabled", "Diploma", "Engineering"], "ministry": "AICTE", "benefits": "Pragati: Rs. 50,000 per year for girls in technical education (diploma/degree). Saksham: Rs. 50,000 per year for differently-abled students in technical education. Covers tuition + incidentals for AICTE-approved courses including polytechnic diploma", "description": "AICTE Pragati scholarship for girl students and Saksham scholarship for differently-abled students pursuing technical education in AICTE-approved institutions. Covers polytechnic diploma courses, engineering degree, MBA, MCA, architecture, pharmacy, and hotel management. Eligibility: Pragati — girl students, family income below Rs. 8 lakhs/year. Saksham — differently abled students (40%+ disability), family income below Rs. 8 lakhs/year. Apply through AICTE portal. 2 children max per family eligible.", "source_url": "https://www.aicte-india.org/schemes/students-development-schemes", "source_type": "portal", "eligibility": "Pragati: Girl students, income below Rs. 8L. Saksham: 40%+ disability, income below Rs. 8L", "documents_required": "Aadhaar, Income certificate, Admission letter, Community/disability certificate, Bank passbook", "application_mode": "Online via AICTE portal"},

    {"name": "TN Free Breakfast + Lunch for Polytechnic Students", "slug": "tn-free-meals-polytechnic-hostel", "state": "Tamil Nadu", "category": ["Education", "Polytechnic", "Nutrition", "Hostel"], "ministry": "Department of Technical Education, Tamil Nadu", "benefits": "Free or subsidized hostel accommodation + meals for government polytechnic college students from BC/MBC/SC/ST categories. Hostel fee as low as Rs. 150-300/month at government polytechnics.", "description": "Government polytechnic colleges in Tamil Nadu provide subsidized hostel accommodation and free/subsidized meals for students from economically weaker sections. SC/ST students get free hostel in many government polytechnics. BC/MBC students get highly subsidized hostel. This is separate from the scholarship — students can get both hostel benefit AND scholarship simultaneously.", "source_url": "https://www.tndte.gov.in", "source_type": "portal", "eligibility": "Government polytechnic student, BC/MBC/SC/ST, Tamil Nadu native", "documents_required": "College admission letter, Community certificate, Income certificate, Aadhaar", "application_mode": "Through polytechnic college admission office"},

    {"name": "PM Yasasvi Scholarship (OBC/EBC/DNT)", "slug": "pm-yasasvi-scholarship", "state": "Central", "category": ["Education", "Scholarship", "OBC", "EBC", "BC", "Diploma"], "ministry": "Ministry of Social Justice & Empowerment", "benefits": "Rs. 75,000 per year for professional courses (diploma, degree, engineering, medical) and Rs. 25,000 for non-professional courses for OBC/EBC/DNT students. Covers polytechnic diploma students", "description": "PM-YASASVI (Young Achievers Scholarship Award for Vibrant India) for OBC, EBC (Economically Backward Classes), and DNT (De-notified Tribes) students. Eligibility: OBC/EBC/DNT category, family income below Rs. 2.5 lakhs/year, studying in recognized institution at post-matric level. Covers polytechnic diploma, ITI, engineering, medical, and all professional courses. Apply through National Scholarship Portal. This is the renamed and enhanced version of the earlier Post-Matric Scholarship for OBC.", "source_url": "https://scholarships.gov.in", "source_type": "portal", "eligibility": "OBC/EBC/DNT category, Family income below Rs. 2,50,000/year, Post-matric student", "documents_required": "OBC/EBC/DNT certificate, Income certificate (below 2.5L), Aadhaar, Mark sheets, Bank passbook, Bonafide", "application_mode": "Online via https://scholarships.gov.in (NSP)"},

    {"name": "TN e-Sevai Scholarship Portal", "slug": "tn-e-sevai-scholarship", "state": "Tamil Nadu", "category": ["Education", "Scholarship", "Portal", "BC", "MBC", "SC"], "ministry": "Tamil Nadu Government", "benefits": "Single window portal for all TN government scholarships — BC/MBC scholarship, SC/ST scholarship, minority scholarship, merit scholarship. Students can apply for multiple scholarships through one portal", "description": "Tamil Nadu e-Scholarship portal (https://escholarship.tn.gov.in) is the unified platform for applying to all state government scholarships. Students pursuing polytechnic diploma, degree, engineering, medical, and other courses can apply for: BC/MBC Post-Matric Scholarship, SC/ST Post-Matric Scholarship, First Graduate Scholarship, and other state schemes. Application opens typically in August-September each year. Students should apply within 30 days of admission. Required: Community certificate, income certificate, Aadhaar-linked bank account, institution bonafide.", "source_url": "https://escholarship.tn.gov.in", "source_type": "portal", "eligibility": "Tamil Nadu domicile, Post-matric student, Various category-specific requirements", "documents_required": "Community certificate, Income certificate, Aadhaar, Bank passbook, Mark sheets, Bonafide", "application_mode": "Online via https://escholarship.tn.gov.in"},

    {"name": "TN First Graduate Scholarship", "slug": "tn-first-graduate-scholarship", "state": "Tamil Nadu", "category": ["Education", "Scholarship", "First Graduate", "Diploma", "Degree"], "ministry": "Tamil Nadu Higher Education Department", "benefits": "Special scholarship for first-generation graduates — students who are the first in their family to pursue higher education (diploma/degree/professional course). Monthly stipend + tuition fee support for polytechnic and degree students", "description": "Tamil Nadu First Graduate Scholarship for students who are the first person in their family to pursue higher education. Applicable to polytechnic diploma, UG degree, PG, and professional courses. No specific income limit in many cases but preference given to economically weaker first-generation learners. Apply through TN e-Scholarship portal. Students in government polytechnics pursuing diploma in CSE, Mechanical, Civil, ECE, EEE, and other branches are eligible.", "source_url": "https://escholarship.tn.gov.in", "source_type": "portal", "eligibility": "First in family to pursue higher education, Tamil Nadu native, Studying diploma/degree/professional course", "documents_required": "First graduate certificate, Community certificate, Income certificate, Aadhaar, Bank passbook, Mark sheets", "application_mode": "Online via https://escholarship.tn.gov.in"},
]
